server:
  port: 8092

spring:
  application:
    name: course
  datasource:
    url: jdbc:mysql://mariadb-school:3306/course?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    password: admin
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

feign:
  client:
    config:
      default :
        connect-timeout: 160000000
        read-timeout: 160000000
