server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: etudiant
          uri: lb://ETUDIANT
          predicates:
            - Path=/etudiants/**
        - id: professor
          uri: lb://PROFESSOR
          predicates:
            - Path=/professors/**
        - id: course
          uri: lb://COURSE
          predicates:
              - Path=/courses/**
              - Path=/studentCourses/**
  zipkin:
    base-url: http://localhost:9411


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/