server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: etudiant
          uri: lb://ETUDIANT
          predicates:
            - Path=/etudiants/**
        - id: professor
          uri: lb://PROFESSOR
          predicates:
            - Path=/professors/**
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka