server:
  port: 8088

spring:
  application:
    name: produit
  datasource:
    url: jdbc:mysql://localhost:3306/produit?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    password: admin
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  graphql:
    graphiql:
      enabled: true
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
