spring:
  kafka:
    bootstrap-servers: http://localhost:29092
  zipkin:
    base-url: http://localhost:9411
  application:
    name: kafka-producer
server:
  port: 8085
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/