version: "3.7"
services:
  mariadb-school:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER:  admin
      MYSQL_PASSWORD: admin
    expose:
      - "40000"
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql2
    networks:
      - ${GLOBAL_NETWORK:-services}

  phpmyadmin-school:
    image: phpmyadmin
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    depends_on:
      - mariadb-school
    networks:
      - ${GLOBAL_NETWORK:-services}
volumes:
  mariadb:
    driver: local
