version: '3.7'
services:
  eureka-server:
    image: 2001daa/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ${GLOBAL_NETWORK:-spring}
    depends_on:
      - zipkin
  apigw:
    image: 2001daa/apigw:latest
    container_name: apigw
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ${GLOBAL_NETWORK:-spring}
    depends_on:
      - zipkin
      - eureka-server
  student:
    image: 2001daa/student-service:latest
    container_name: customer
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ${GLOBAL_NETWORK:-spring}
    depends_on:
      - zipkin
      - eureka-server
      - mariadb-school